### ISSUE TITLE
Annotations of objects in Scala 3 enums not discovered

### ISSUE THREAD

**Issue by schmeedy** [typelevel/shapeless-3#106]
Consider the following enum declared in tests for annotations:
```scala
  @Other @Last(false) enum Control:
    @First @Third('!') case Automatic
    @Second(100, "@") case Manual(age: PosInt, email: Email)
```

The expression `Annotations[First, Control].apply()` evaluates to `(None, None)` instead of the expected `(Some(First), None)`. Only annotations for cases without parameters declared as Scala 3 enums are affected. Both `Annotations` of parameterized enum cases and explicit case objects inheriting from a sealed trait are discovered correctly.

**Comment by joroKr21** [comment]
Most surely a bug. One difference is that enum cases without parameters are implemented as `val`s underneath, not objects. So the question then is where the annotation is stored and how to get it.

**Comment by joroKr21** [comment]
It would be good to check if the same problem exists for:
 * `Annotation`
 * `AllAnnotations`
 * `TypeAnnotations`
 * `AllTypeAnnotations`

**Comment by schmeedy** [comment]
Both `TypeAnnotations` and `AllTypeAnnotations` don't discover type annotations attached to parameterless enum cases. `AllAnnotations` returns annotations placed on the enum itself instead of annotations of any parameterless case.
