### ISSUE TITLE
Expose deriving.internals.ReflectionUtils

### ISSUE THREAD

**Issue by chuwy** [typelevel/shapeless-3#133]
Hey! 

I'm wondering if there are strong reasons to hide such an awesome utility such as [ReflectionUtils](https://github.com/typelevel/shapeless-3/blob/5785c84e85328cc7e19270f30c943efc1cca2f08/modules/deriving/src/main/scala/shapeless3/deriving/internals/reflectionutils.scala). I believe this is something many people need when they build macros around `Mirror`. I had to re-implement it myself because passing a `Mirror`-based type-class instance into macro could not be inlined - not sure if it was my lack of knowledge or just tricky thing, but nevertheless I couldn't workaround and `ReflectionUtils` saved the day.

Also ducktape uses it: https://github.com/arainko/ducktape/blob/3d7774c1853a85878321724acc0a63a88b202673/ducktape/src/main/scala/io/github/arainko/ducktape/internal/modules/MaterializedMirror.scala

**Comment by joroKr21** [comment]
Maybe we can expose it but Shapeless 2 was very difficult to evolve because all the internals were exposed.

It would warrant a review of what is actually useful and expected to not change.
