### ISSUE TITLE
Issue deriving Generic for ADTs mixed in via traits

### ISSUE THREAD

**Issue by TimWSpence** [typelevel/shapeless-3#30]
I've been investigating functor law failures with https://github.com/typelevel/kittens/pull/362 and it looks like it's related to ADTs defined in traits and then mixed into the scope where the eg `Functor` instance is defined.

After muddling around for a while I started to wonder if shapeless 3 has similar issues and AFAICT it does.

https://github.com/typelevel/shapeless-3/tree/compilation-failure doesn't compile due to
```scala
 val F: Functor[IList] = Functor.derived[IList]
[error]   |                                                ^
[error]   |no implicit argument of type shapeless3.deriving.K1.Generic[Scope.this.IList] was found for parameter gen of method derived in object Functor
[error] one error found
```

the previous commit is almost identical but doesn't define the `IList` ADT in a trait and it compiles fine?

**Comment by TimWSpence** [comment]
Looks like this is caused by https://github.com/lampepfl/dotty/issues/13332

**Comment by joroKr21** [comment]
Yes, the cause is in Dotty
