### ISSUE TITLE
Should ProductInstances be lazy too?

### ISSUE THREAD

**Issue by joroKr21** [typelevel/shapeless-3#40]
Consider the following definition:
```scala
final case class Recursive(i: Int, is: Option[Recursive])
```

Currently type class derivation doesn't work for recursive case classes like this one.
The issue is that only `CoproductInstances` are lazy whereas `ProductInstances` are eager.

**Comment by TimWSpence** [comment]
Resolved by https://github.com/typelevel/shapeless-3/pull/47
