### ISSUE TITLE
Ambiguous implicits for one empty enum case

### ISSUE THREAD

**Issue by sake92** [typelevel/shapeless-3#51]
If you have *exactly one case* with *no parameter list* you get ambiguous implicits.  
If there are 2 cases it works, or if you have empty parens:
```scala
enum Works1 derives Eq:
  case Red, Blue

enum Works2 derives Eq:
  case Red()

enum Nope derives Eq: // ambigous implicits
  case Red
```

Not sure if there's any workarounds, first time I'm using shapeless.  
Amazing library btw! 😃 

Repro:
https://scastie.scala-lang.org/edoI6AKPQIKjuFM6vzzsWg

**Comment by andrzejressel** [comment]
I was doing some tests and it seems Shapeless for some reason really does not like enums without type parameters:
- https://github.com/andrzejressel/shapeless-3/commit/0e8df3bde9bb2023eb752e8abc3bd50fc267e82b
- https://github.com/andrzejressel/shapeless-3/commit/ddec85e9e26c53f258872dfc378dd5a3bc3c74a8

**Comment by liewhite** [comment]
It can be workaround by typeclass lookup priority. Such as put product derives and coproduct derives in an object hierarchy

**Comment by joroKr21** [comment]
Fixed upstream - thanks @andrzejressel 🥳 https://github.com/lampepfl/dotty/pull/14525
